# Generated by Django 2.2.13 on 2021-01-16 18:27

from django.db import migrations

from helpers.backend_user_helper import BackendUserHelper


def create_backend_user(apps, schema_editor):
    helper = BackendUserHelper()
    helper.create_user()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210116_1827'),
    ]

    operations = [
        migrations.RunPython(create_backend_user)
    ]
